version: '3'
services:
    django:
        build:
            context: ./portfolio_django/
            dockerfile: dockerfile 
        volumes:
            - ./portfolio_django/:/app/
        ports:
            - "8000:8000"
        command: >
          bash -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8005"
    react:
        build:
            context: ./portfolio_react/
            dockerfile: dockerfile 
        volumes:
          - ./portfolio_react/:/app/
          # If you're using Create React App with npm (also in other cases), you might need this to avoid issues with file watching.
          #- /code/node_modules
        ports:
            - "3000:3000"
